CREATE TABLE USUARIO(
    ID_USUARIO VARCHAR2(10),
    PASSWD VARCHAR2(10),
    CONSTRAINT USR_ID_US_PK PRIMARY KEY (ID_USUARIO),
    CONSTRAINT USR_PWD_NN NOT NULL
);


CREATE TABLE COMPRA(
    ID_COMPRA NUMBER(20),
    FECHA_COMPRA DATE,
    IMPORTE NUMBER (10,2),
    ID_USUARIO VARCHAR2(10),
    CONSTRAINT COMP_ID_COM_PK PRIMARY KEY (ID_COMPRA),
    CONSTRAINT COMP_FEC_COM_CHK CHECK (FECHA_COMPRA >= SYSDATE),
    CONSTRAINT COMP_IMP_COM_CHK CHECK (IMPORTE > 0),
    CONSTRAINT COMP_ID_US_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO)
);


CREATE TABLE PRODUCTO(
    ID_PRODUCTO VARCHAR2(20),
    NOMBRE VARCHAR2(20),
    TIPO VARCHAR2(20),
    PRODUCTO_MEDICO BOOLEAN,
    NOMBRE VARCHAR2(20),
    CONSTRAINT PROD_ID_PROD_PK PRIMARY KEY (ID_PRODUCTO),
);


CREATE TABLE GESTION_STOCK (
    ID_USUARIO VARCHAR2(10),
    ID_PRODUCTO VARCHAR2(20),
    FECHA_GESTION DATE,
    CANTIDAD NUMBER(4),
    CONSTRAINT GST_ST_FEC_GST_NN NOT NULL,
    CONSTRAINT GST_ST_CNT_NN NOT NULL,
    CONSTRAINT GST_ST_ID_USR_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO (ID_USUARIO),
    CONSTRAINT GST_ST_ID_PRD_FK FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO)  
);


CREATE TABLE CONTROLA (
    ID_COMPRA NUMBER(20),
    ID_PRODUCTO VARCHAR2(20),
    CONSTRAINT CNT_ID_COM_FK FOREIGN KEY (ID_COMPRA) REFERENCES COMPRA (ID_COMPRA),
    CONSTRAINT CNT_ID_PRD_FK FOREIGN KEY (ID_PRODUCTO) PRODUCTO(ID_PRODUCTO)
);